"use client";

import { useEffect } from "react";
import { apiFetch } from "@/lib/api/client";

type ThemeSettings = {
  theme_color_primary?: string;
  theme_color_action?: string;
  theme_color_gold?: string;
};

/**
 * Every color utility in this app (bg-ink-900, text-forest-600, bg-gold-500...)
 * is generated by Tailwind from the --color-* custom properties defined in
 * globals.css. Overriding those same variable names on :root at runtime — after
 * fetching admin-set values — re-themes the entire site without touching a
 * single component. Falls back silently to the compiled defaults if the
 * fetch fails or a color hasn't been customized.
 */
export function ThemeProvider() {
  useEffect(() => {
    apiFetch<ThemeSettings>("/settings?group=theme")
      .then((settings) => {
        const root = document.documentElement;
        if (settings.theme_color_primary) {
          root.style.setProperty("--color-ink-900", settings.theme_color_primary);
        }
        if (settings.theme_color_action) {
          root.style.setProperty("--color-forest-600", settings.theme_color_action);
        }
        if (settings.theme_color_gold) {
          root.style.setProperty("--color-gold-500", settings.theme_color_gold);
        }
      })
      .catch(() => {
        // Compiled defaults from globals.css already apply — nothing to do.
      });
  }, []);

  return null;
}
